spring.application.name=backend

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/eat_club_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

app.jwt.secret=hclhackathonproblemstatementfooddeliveryapp1234
app.jwt.expiration-millis=86400000
