spring.application.name=backend

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/eatclub_db
spring.datasource.username=root
spring.datasource.password=SHREE@28s05
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

app.jwt.secret=hclhackathonproblemstatementfooddeliveryapp1234
app.jwt.expiration-millis=86400000

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.doc-expansion=list
springdoc.show-actuator=false
springdoc.api-docs.enabled=true
